### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by rafde** [jmeas/marionette.base-view#11]
I remember you mentioning this some time ago but I was unsure if this is ready for use now.

**Comment by megawac** [comment]
Hey rafde most of this work has been moved over to the marionettejs v3 branch I believe

**Comment by jamesplease** [comment]
Yo @rafde! :wave:

I'm using this in one app in production, and it's been going well. I strongly recommend that one read through the source / understand exactly what the code is doing before deciding to use it. [It's only a few lines long luckily](https://github.com/jmeas/marionette.base-view/blob/master/src/marionette.base-view.js)!

Another thing to keep in mind is that it's not compatible with Marionette v2's API. This lib returns the view from `showChildView`, while Marionette returns the Region. That's one little detail that might hang someone up if they're chaining, like:

``` js
this.showChildView( ... ).someRegionMethod();
```

**Comment by rafde** [comment]
Thanks for the response. I read through the file and it's pretty straight forward.
If you recall my work's code base, chaining is a rarity. And it's even rarer to chain regions.
Since there's a MarionetteV3 branch, I might check that out for reference.
Thanks again.

**Comment by megawac** [comment]
Here's the branch if you go looking for it
https://github.com/marionettejs/backbone.marionette/tree/next

**Comment by rafde** [comment]
Thanks @megawac , I looked through the change diff https://github.com/marionettejs/backbone.marionette/compare/2.4.2...next#diff-b8da5292cb07ec757ac64e78ff5af5c1 and didn't see the next code reflect what this code base is doing. It looks like you still have to use the `regions` hash or `#addRegion` function. No big deal. It was out of curiosity that I ask anyhow. Thanks.
